envVarGroups:
  - name: view-and-review-env
    envVars:
    - key: DJANGO_MIGRATE_DB_ON_STARTUP
      value: 1
    - key: DEBUG
      value: 0
    - key: DJANGO_SETTINGS_MODULE
      value: project.settings.deps
    - key: DJANGO_SUPERUSER_USERNAME
      sync: false
    - key: DJANGO_SUPERUSER_PASSWORD
      sync: false
    - key: DJANGO_SUPERUSER_EMAIL
      sync: false
    - key: PORT
      sync: false
    - key: ALLOWED_HOSTS
      sync: false
    - key: TMDB_API_KEY
      sync: false
    - key: TMDB_BEARER_TOKEN
      sync: false
    - key: DJANGO_EMAIL_USER
      sync: false
    - key: DJANGO_EMAIL_PASSWORD
      sync: false
    - key: DATABASE_URL
      sync: false
    - key: SECRET_KEY
      generateValue: true

services:
  - type: web
    plan: free
    name: view-and-review
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    repo: https://github.com/GEI-WP/view-and-review
    region: frankfurt
    branch: main
    rootDir: django
    healthCheckPath: /health
