from .dep import *

# Security

# CSP
CSP_UPGRADE_INSECURE_REQUESTS = True

# HSTS
SECURE_HSTS_SECONDS = 15768000 # 6 months
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Cookie Options
SESSION_COOKIE_SECURE = True
