FROM python:3.10-slim

EXPOSE 8000

# Install development dependencies
RUN echo "deb http://deb.debian.org/debian/ unstable main contrib non-free" >> /etc/apt/sources.list.d/debian.list

RUN apt update && \
    apt install -y make \
    --no-install-recommends firefox

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install python packages
RUN pip install poetry

# Set current working directory
WORKDIR /app/django

# Copy only requirements to cache them in docker layer
COPY poetry* pyproject* ./

# Project initialization
RUN poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-ansi

# Copy files
COPY . .

# Change PATH for installing geckodriver
ENV PATH=${PATH}:./

ENTRYPOINT [ "./entrypoint.sh" ]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]