run:
	python /app/django/manage.py runserver 0.0.0.0:8000

migrations:
	python /app/django/manage.py makemigrations --no-input

migrate:
	python /app/django/manage.py migrate --no-input

static:
	python /app/django/manage.py collectstatic --no-input

clean:
	rm -rf staticfiles