# Generated by Django 4.1.7 on 2023-05-11 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.TextField(max_length=40000, validators=[django.core.validators.int_list_validator])),
                ('favlist', models.TextField(max_length=40000, validators=[django.core.validators.int_list_validator])),
            ],
        ),
    ]
