# Generated by Django 4.1.7 on 2023-04-04 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='film',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.film'),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.DecimalField(choices=[(0, 0), (0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='rating',
            name='site',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.film'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.rating'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
