# Generated by Django 4.1.7 on 2023-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_myprofile_favlist_alter_myprofile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
