# Generated by Django 4.1.7 on 2023-04-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
