# Generated by Django 4.1.7 on 2023-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo_url',
            field=models.URLField(default=''),
        ),
    ]
