# Generated by Django 4.1.7 on 2023-04-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_film_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='site',
        ),
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.film'),
        ),
    ]
