# Generated by Django 4.1.7 on 2023-04-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_rating_site_alter_rating_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(choices=[(0.0, 0.0), (0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, default=(0.0, 0.0), max_digits=2),
        ),
    ]
