# Generated by Django 4.1.7 on 2023-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rating_review_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(choices=[(0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0)], decimal_places=1, default=(0.0, 0.0), max_digits=2),
        ),
    ]
