# Generated by Django 4.1.7 on 2023-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
