# Generated by Django 4.1.7 on 2023-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_rating_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
