# Generated by Django 4.1.7 on 2023-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_rating_reputation_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='film',
            name='languages',
        ),
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
