# Generated by Django 4.1.7 on 2023-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_film_actors_remove_film_directors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.PositiveBigIntegerField(),
        ),
    ]
