# Generated by Django 4.1.7 on 2023-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_rating_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
